blank_issues_enabled: false
contact_links:
    - name: Questions or discussion?
      url: https://join.slack.com/t/webcomponentcommunity/shared_invite/zt-uinb2qud-cDvio5cC7IllxZfcTFf4QQ 
      about: Please post general questions or discussion topics here.
